apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://sonatype.github.io/helm3-charts
    chart: nexus-repository-manager
    targetRevision: 42.0.0
    helm:
      releaseName: nexus
      values: |-
        ingress:
          enabled: true
          annotations: 
            kubernetes.io/ingress.class: nginx
          hostPath: /
          hostRepo: nexus.minikube.local
          ingressClassName: nginx
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          storageClass: standard
          storageSize: 30Gi
        serviceAccount:
          create: true
          annotations: {}
          name: "nexus-sa"
        nexus:
          nodeSelector: {}
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
